var fake_gm_list = {
    "Animals": [
        "Lion",
        "Tiger",
        "Bear",
        "Chicken",
        "Owl",
        "Penguin",
        "Turkey",
        "Alligator",
        "Butterfly",
        "Caterpillar",
        "Fly",
        "Frog",
        "Dragonfly",
        "Grasshopper",
        "Ladybug",
        "Lizard",
        "Cockroach",
        "Spider",
        "Snake",
        "Turtle",
        "Boar",
        "Beaver",
        "Camel",
        "Cow",
        "Cat",
        "Deer",
        "Dog",
        "Horse",
        "Elephant",
        "Giraffe",
        "Fox",
        "Gorilla",
        "Hippo",
        "Lamb",
        "Kangaroo",
        "Raccoon",
        "Seal",
        "Rabbit",
        "Porcupine",
        "Zebra",
        "Lobster",
        "Shrimp",
        "Octopus",
        "Seahorse",
        "Starfish",
    ],
    "Plants": [
        "Pine Tree",
        "Cactus",
        "Poison Ivy",
        "Dandelion",
        "Fern",
        "Root",
        "Sunflower",
        "Rose",
        "Bush",
        "Leaf",
        "Vine",
        "Tree",
    ],
    "Foods": [
        "Apple",
        "Spaghetti",
        "Steak",
        "Clams",
        "Sushi",
        "Potatoes",
        "Burger",
        "Hoagie",
        "Herbs",
        "Avocado",
        "Banana",
        "Pineapple",
        "Raspberries",
        "Watermelon",
        "Blueberries",
        "Nuts",
        "Bread",
        "Toast",
        "Bacon",
        "Eggs",
    ],
    "Drinks": [
        "Soda",
        "Beer",
        "Wine",
        "Liquor",
        "Juice",
        "Coffee",
        "Tea",
        "Champagne",
    ],
    "Outdoor Gear": [
        "Backpack",
        "Binoculars",
        "Blanket",
        "Camp Stove",
        "Beach Towel",
        "Cooler",
        "Surf Board",
        "Basketball",
        "Volley Ball",
        "Baseball",
        "Dumb Bell",
        "Golf Club",
        "Fishing Rod",
        "Swimsuit",
        "Bicycle",
    ],
    "Musical Instruments": [
        "Accordion",
        "Banjo",
        "Bongo",
        "Bugle",
        "Trumpet",
        "Drum",
        "Guitar",
        "Saxophone",
        "Organ",
        "Trombone",
        "Tuba",
        "Cello",
    ],

}