var fake_gm_list = {
    "Animals": [
        "Lion",
        "Tiger",
        "Bear",
        "Chicken",
        "Owl",
        "Penguin",
        "Turkey",
        "Alligator",
        "Butterfly",
        "Caterpillar",
        "Fly",
        "Frog",
        "Dragonfly",
        "Grasshopper",
        "Ladybug",
        "Lizard",
        "Cockroach",
        "Spider",
        "Snake",
        "Turtle",
        "Boar",
        "Beaver",
        "Camel",
        "Cow",
        "Cat",
        "Deer",
        "Dog",
        "Horse",
        "Elephant",
        "Giraffe",
        "Fox",
        "Gorilla",
        "Hippo",
        "Lamb",
        "Kangaroo",
        "Raccoon",
        "Seal",
        "Rabbit",
        "Porcupine",
        "Zebra",
        "Lobster",
        "Shrimp",
        "Octopus",
        "Seahorse",
        "Starfish",
    ],
    "Plants": [
        "Pine Tree",
        "Cactus",
        "Poison Ivy",
        "Dandelion",
        "Fern",
        "Root",
        "Sunflower",
        "Rose",
        "Bush",
        "Leaf",
        "Vine",
        "Tree",
    ],
    "Foods": [
        "Apple",
        "Spaghetti",
        "Steak",
        "Clams",
        "Sushi",
        "Potatoes",
        "Burger",
        "Hoagie",
        "Herbs",
        "Avocado",
        "Banana",
        "Pineapple",
        "Raspberries",
        "Watermelon",
        "Blueberries",
        "Nuts",
        "Bread",
        "Toast",
        "Bacon",
        "Eggs",
    ],
    "Drinks": [
        "Soda",
        "Beer",
        "Wine",
        "Liquor",
        "Juice",
        "Coffee",
        "Tea",
        "Champagne",
    ],
    "Outdoor Gear": [
        "Backpack",
        "Binoculars",
        "Blanket",
        "Camp Stove",
        "Beach Towel",
        "Cooler",
        "Surf Board",
        "Basketball",
        "Volley Ball",
        "Baseball",
        "Dumbbell",
        "Golf Club",
        "Fishing Rod",
        "Swimsuit",
        "Bicycle",
    ],
    "Musical Instruments": [
        "Accordion",
        "Banjo",
        "Bongo",
        "Bugle",
        "Trumpet",
        "Drum",
        "Guitar",
        "Saxophone",
        "Organ",
        "Trombone",
        "Tuba",
        "Cello",
    ],
    "Body Parts": [
        "Armpit",
        "Back",
        "Butt",
        "Ears",
        "Eyes",
        "Feet",
        "Face",
        "Fingers",
        "Foot",
        "Hand",
        "Hair",
        "Knees",
        "Legs",
        "Mouth",
        "Toes",
        "Brain",
        "Heart",
        "Teeth",
        "Thumb",
        "Lungs",
        "Intestines",
    ],
    "Buildings": [
        "Bakery",
        "Cafe",
        "Church",
        "Movie Theatre",
        "Book Store",
        "Barber Shop",
        "Airport",
        "Castle",
    ],
    "Household Items": [
        "Broom",
        "Mop",
        "Blender",
        "Toaster",
        "Knife",
        "Lock and Key",
        "Pencil",
        "Pen",
        "Mug",
        "Salt and Pepper",
        "Pitcher",
        "Oven Mitt",
        "Oven",
        "Refrigerator",
        "Sink",
        "Toilet",
        "Plate",
        "Fork",
        "Spoon",
        "Chopsticks",
        "Bowl",
        "Gun",
        "Shovel",
        "Hammer",
        "Wrench",
        "Nail",
        "Saw",
        "Axe",
        "Ruler",
        "Bottle",
        "Bed",
        "Couch",
        "Chair",
        "Computer Mouse",
        "Computer",
        "Floppy Disk",
        "CD ROM",
        "Computer Keyboard",
        "Phone",
        "Ladder",
    ],
    "Countries": [
        "United States",
        "Canada",
        "Mexico",
        "Italy",
        "United Kingdom",
        "Germany",
        "Russia",
        "Australia",
        "Brazil",
        "India",
    ],
    "Landmarks": [
        "Mount Rushmoore",
        "Egyptian Pyramids",
        "Eiffel Tower",
        "Statue of Liberty",
        "Grand Canyon",
        "Big Ben",
        "Space Needle",
        "Taj Mahal",
        "Niagra Falls",
    ],
    "Flags": [
        "United States",
        "Canada",
        "United Kingdom",
        "European Union",
        "Switzerland",
        "Korea",
        "Japan",
        "China",
        "Australia",
    ],
    "Professions": [
        "Cowboy",
        "Doctor",
        "Firefighter",
        "Mail Carrier",
        "Hacker",
        "Seamstress",
        "Dentist",
        "Police Officer",
        "Plumber",
        "Construction Worker",
        "Football Player",
    ],
    "Cowboy Gear": [
        "10 Gallon Hat",
        "Bullet",
        "Pistol",
        "Bandolier",
        "Horse",
        "Saddle",
        "Holster",
        "Rifle",
        "Lasso",
        "Boots",
    ],
    "Transportation": [
        "Car",
        "Boat",
        "Airplane",
        "Truck",
        "Buss",
        "Train",
        "Railroad",
    ],
    "Weapons": [
        "Bomb",
        "Bow and Arrow",
        "Cannon",
        "Spear",
        "Tank",
        "Sword",
        "Shield",
        "Hand Grenade",
        "Gun",
        "Axe",
        "Slingshot",
        "Raygun",
    ]
}